--[[
                        *** DO NOT EDIT ***

    This Lua template module was generated by the Lemplate compiler.

    Copyright 2017. OpenResty Inc. All rights reserved.
]]


-- Define top level namespaces --

local Lemplate = {}
local Template = {}
local Filter = {}
local Vmethod = {}
local MD5 = {}


-- Define common internal worker functions --

local concat = table.concat
local find = ngx.re.find
local gsub = ngx.re.gsub
local lower = string.lower
local match = ngx.re.match
local maxn = table.maxn
local noop = function() return '' end
local split_ = require("ngx.re").split
local sub = ngx.re.sub
local substr = string.sub
local upper = string.upper


-- Define top level local variables --

local render
local recurse_limit = 100
local recurse_depth
local iterate_limit = 10000
local iterate_count


-- Define the Lemplate API exports --

-- `process()` is the Lemplate function to render a template:
Lemplate.process = function (template, data)
    data = data or {}

    recurse_depth = 0
    iterate_count = 0

    return render(template, data)
end

Lemplate.md5hex = function (template)
    return MD5[template]
end

-- User API for custom filters:
Lemplate.filters = Filter

-- User API for custom vmethods:
Lemplate.vmethods = Vmethod



-- Define internal runtime functions --

-- Get a value from the "stash" namespace:
local get = function (stash, name)
    local value = stash[name]

    if value == nil then
        return ''
    end

    if type(value) ~= 'function' then
        return value
    end

    return value()
end

-- Get a value from the "stash" namespace using a variable key:
local getvar = function (stash, name)
    if find(name, '^[0-9]+$', 'jo') then
        name = name + 1
    end

    return (stash[name] or '')
end

-- Set a value in the "stash" namespace:
local set = function (stash, name, value)
    stash[name] = value

    return ''
end

-- Set *default* value in the "stash" namespace:
local defvar = function (stash, name, value)
    if stash[name] == nil then
        stash[name] = value
    end

    return ''
end

-- Test the Perl5/TT2 truthiness of something:
local tru = function (x)
    return x and x ~= '' and x ~= 0 and x ~= '0'
end

-- Iterate over an array:
local each = function (array)
    local i = 0

    return function ()
        iterate_count = iterate_count + 1
        if iterate_count > iterate_limit then
            error("Maximum iteration limit '"..iterate_limit.."' exceeded")
        end

        i = i + 1
        return array[i]
    end
end

-- Make a shallow clone of the stash for INCLUDEs:
local clone = function (stash)
    local clone = {}

    for key, value in pairs(stash) do
        clone[key] = value
    end

    return clone
end

local merge = function (hash, more)
    for k, v in pairs(more) do
        hash[k] = v
    end

    return hash
end

-- Call a render function, but watch the recursion depth:
render = function (name, data)
    recurse_depth = recurse_depth + 1
    if recurse_depth > recurse_limit then
        error("Maximum recursion depth '"..recurse_limit.."' exceeded")
    end

    local rendering = Template[name](data)

    recurse_depth = recurse_depth - 1

    return concat(rendering)
end

-- Render a named template, localizing the stash first:
local include = function (stash, name)
    return render(name, clone(stash))
end

-- Render a named template, localizing the stash first, then adding
-- variable assignments:
local include_plus = function (stash, name, assigns)
    return render(name, merge(clone(stash), assigns))
end

-- Render a named template, without localizing the stash first:
local process = function (stash, name)
    return render(name, stash)
end

-- Render a named template, without localizing the stash first, then
-- adding variable assignments:
local process_plus = function (stash, name, assigns)
    return render(name, merge(stash, assigns))
end

-- TT vmethod functions --

-- First element of an array:
local first = function (array)
    if type(array) ~= 'table' then return '' end

    return array[1]
end

-- Join an array by a separator string:
local join = function (array, sep)
    if type(array) ~= 'table' then return '' end

    return concat(array, sep)
end

-- Keys of a hash (as an array):
local keys = function (hash)
    if type(hash) ~= 'table' then return '' end

    local out = {}
    local i = 0

    for key in pairs(hash) do
        i = i + 1
        out[i] = key
    end

    table.sort(out)

    out[0] = i

    return out
end

-- Last element of an array:
local last = function (array)
    if type(array) ~= 'table' then return '' end

    if array[0] == nil then array[0] = maxn(array) end

    return array[array[0]]
end

-- Push one or more values onto an array:
local push = function (array, ...)
    if type(array) ~= 'table' then return '' end

    local len = array[0]
    if len == nil then len = maxn(array) end

    for i = 1, select("#", ...) do
        len = len + 1
        array[len] = select(i, ...)
    end

    array[0] = len

    return ''
end

-- Size of an array:
local size = function (array)
    if type(array) == 'table' then
        if array[0] == nil then array[0] = maxn(array) end
        return array[0]
    else
        return ''
    end
end

-- Sort an array:
local sort = function (array)
    if type(array) ~= 'table' then return '' end

    local out = {}
    if array[0] == nil then array[0] = maxn(array) end
    local size = array[0]
    table.move(array, 1, size, 1, out)
    table.sort(out)
    out[0] = size
    return out
end

-- Split a string on a delimiter into an array:
local split = function (str, delim)
    delim = delim or ' '
    local array = split_(str, delim)
    array[0] = maxn(array)
    return array
end


-- Standard Lemplate filter functions --

Filter.html = function (str)
    str = gsub(str, '&', '&amp;', 'jo')
    str = gsub(str, '<', '&lt;', 'jo')
    str = gsub(str, '>', '&gt;', 'jo')
    str = gsub(str, '"', '&quot;', 'jo')
    return str
end

Filter.lcfirst = function (str)
    return sub(str, '^(.)', function (m) return lower(m[1]) end, 'jo')
end

Filter.lower = function (str)
    return lower(str)
end

Filter.trim = function (str)
    str = sub(str, '^\\s+', '', 'jo')
    str = sub(str, '\\s+$', '', 'jo')
    return str
end

Filter.ucfirst = function (str)
    return sub(str, '^(.)', function (m) return upper(m[1]) end, 'jo')
end

Filter.upper = function (str)
    return upper(str)
end


-- Define all the Lemplate templates as functions --

Template['404.tt2'] = function (stash)
    local out = {}
    local i = 0
    i=i+1 out[i] = "\n<h2>\n404 not found!\n</h2>\n"

    return out
end

MD5['404.tt2'] = "b99354b95a7746ba11d56e93805b1ea4"

Template['analytics.tt2'] = function (stash)
    local out = {}
    local i = 0
    i=i+1 out[i] = "\n<script>\nvar ga_func = function () {\n    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){\n        (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),\n    m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)\n    })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');\n\n    ga('create', 'UA-24724965-2', 'auto');\n    ga('send', 'pageview');\n}\nsetTimeout(ga_func, 0);\n</script>\n"

    return out
end

MD5['analytics.tt2'] = "1607947fa9095b1ca98bcb937e3f82e9"

Template['docs.tt2'] = function (stash)
    local out = {}
    local i = 0
    i=i+1 out[i] = "\n<div class=\"main_col\">\n<div class=\"split_header\">\n    <h2>Docs</h2>\n</div>\n\n"
    i=i+1 out[i] = get(stash, 'doc_html')
    i=i+1 out[i] = "\n</div>\n"

    return out
end

MD5['docs.tt2'] = "d88bd5cfcc7c8303bd681410e8bf5bc3"

Template['error.tt2'] = function (stash)
    local out = {}
    local i = 0
    i=i+1 out[i] = "\n<div class=\"main_col\">\n<div class=\"split_header\">\n    <h2>Error</h2>\n</div>\n\n<div class=\"error_info\">\n    "
    i=i+1 out[i] = Filter.html(get(stash, 'error_info'))
    i=i+1 out[i] = "\n</div>\n\n</div>\n"

    return out
end

MD5['error.tt2'] = "919bb56ddb83e7db9e15f28c1d1559a3"

Template['footer.tt2'] = function (stash)
    local out = {}
    local i = 0
    i=i+1 out[i] = "\n<p>"
    i=i+1 out[i] = "Copyright © 2016-2021 Yichun Zhang (agentzh)"
    i=i+1 out[i] = "</p>\n<p>"
    i=i+1 out[i] = "100% Powered by OpenResty and PostgreSQL"
    i=i+1 out[i] = "\n "
    i=i+1 out[i] = "("
    i=i+1 out[i] = "<a href=\"https://github.com/openresty/opm/\">"
    i=i+1 out[i] = "view the source code of this site"
    i=i+1 out[i] = "</a>"
    i=i+1 out[i] = ")"
    i=i+1 out[i] = "</p>\n<p>京ICP备16021991号</p>"

    return out
end

MD5['footer.tt2'] = "829f51d1ed24690e532b6aac33db9af0"

Template['index.tt2'] = function (stash)
    local out = {}
    local i = 0
    i=i+1 out[i] = "\n<div class=\"intro_banner\">\n    <div class=\"intro_banner_inner\">\n        <div class=\"intro_text\">\n        <p><b>opm</b> is the official OpenResty package manager, similar to Perl's CPAN and NodeJS's npm in rationale.</p>\n        <p>We provide both the opm client-side command-line utility and the server-side application for the central package repository.</p>\n        <p>Please read the <a href=\"/docs\">opm documentation</a> for more details.</p>\n        <p>We already have <b>"
    i=i+1 out[i] = get(stash, 'total_uploads')
    i=i+1 out[i] = "</b> successful uploads across <b>"
    i=i+1 out[i] = get(stash, 'package_count')
    i=i+1 out[i] = "</b> distinct package names from <b>"
    i=i+1 out[i] = get(stash, 'uploader_count')
    i=i+1 out[i] = "</b> contributors. Come on, OPM authors!</p>\n        </div>\n    </div>\n</div>\n\n<div class=\"main_col\">\n<div class=\"split_header\">\n    <h2>Recent packages</h2>\n    <span class=\"header_sub\">\n        (<a href=\"/packages\">view all</a>)\n    </span>\n    <span class=\"right\">\n        <a href=\"/uploads\">Recent uploads</a>\n    </span>\n</div>\n\n<section>\n"
    i=i+1 out[i] = process(stash, "package_list.tt2")
    i=i+1 out[i] = "\n</section>\n</div>\n"

    return out
end

MD5['index.tt2'] = "6a8a43fadabbf26f716cea452f02bdfc"

Template['layout.tt2'] = function (stash)
    local out = {}
    local i = 0
    i=i+1 out[i] = "<!DOCTYPE html>\n<html lang=\"en\">\n<head>\n    <meta charset=\"utf-8\">\n    <title>OPM - OpenResty Package Manager</title>\n    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0, minimum-scale=0.5, maximum-scale=2.0, user-scalable=yes\">\n    <link rel=\"stylesheet\" type=\"text/css\" href=\"/css/main.css\">\n    <script src=\"/js/jquery.min.js\"></script>\n</head>\n<body>\n    <div class=\"content\">\n        <header class=\"header\">\n        "
    i=i+1 out[i] = process(stash, "nav.tt2")
    i=i+1 out[i] = "\n        </header>\n\n        <main class=\"main_page\">\n            "
    i=i+1 out[i] = get(stash, 'main_html')
    i=i+1 out[i] = "\n        </main>\n    </div>\n\n    <div class=\"footer\">\n    "
    i=i+1 out[i] = process(stash, "footer.tt2")
    i=i+1 out[i] = "\n    </div>\n\n"
    i=i+1 out[i] = process(stash, "analytics.tt2")
    i=i+1 out[i] = "\n</body>\n</html>\n"

    return out
end

MD5['layout.tt2'] = "e3c42433ae6f5c54847c751f9e163946"

Template['login.tt2'] = function (stash)
    local out = {}
    local i = 0
    i=i+1 out[i] = "\n<div class=\"main_col\">\n<div class=\"split_header\">\n    <h2>Sign In</h2>\n</div>\n\n<div class=\"sign-in\">\n    <a class=\"button\" href=\""
    i=i+1 out[i] = Filter.html(get(stash, 'github_login_url'))
    i=i+1 out[i] = "\">Sign in with Github</a>\n</div>\n\n</div>\n"

    return out
end

MD5['login.tt2'] = "86993c745d119eb017f6afe74245cf08"

Template['nav.tt2'] = function (stash)
    local out = {}
    local i = 0
    i=i+1 out[i] = "\n<div class=\"header_inner\">\n<a href=\"https://openresty.org\">\n    <img src=\"https://openresty.org/images/logo.png\" width=\"64\">\n</a>\n<nav class=\"logo_panel\">\n<a href=\"/\">\n    OPM\n</a>\n</nav>\n\n<form method=\"GET\" action=\"/search\" class=\"header_search\">\n    <input type=\"text\" placeholder=\"Search Packages ...\" name=\"q\" value=\""
    i=i+1 out[i] = get(stash, 'query_words')
    i=i+1 out[i] = "\">\n</form>\n<nav class=\"nav_panel\">\n    <a href=\"/docs\">Docs</a>"

    if tru(get(stash, 'curr_user')) then
        i=i+1 out[i] = "\n    <span><a href=\""
        i=i+1 out[i] = Filter.html(get(get(stash, 'curr_user'), 'profile_url'))
        i=i+1 out[i] = "\">"
        i=i+1 out[i] = Filter.html(get(get(stash, 'curr_user'), 'login'))
        i=i+1 out[i] = "</a></span>\n    <a href=\"/logout\">Logout</a>"

    else
        i=i+1 out[i] = "\n    <a href=\"/login\">Sign In</a>"
    end

    i=i+1 out[i] = "\n</nav>\n</div>\n"

    return out
end

MD5['nav.tt2'] = "53e85a8509a2a22970e25d29c39d3da1"

Template['package_info.tt2'] = function (stash)
    local out = {}
    local i = 0
    i=i+1 out[i] = "\n<div class=\"main_col package_page\">\n<div class=\"split_header\">\n    <h2>"
    i=i+1 out[i] = Filter.html(get(stash, 'pkg_name'))
    i=i+1 out[i] = "\n    </h2>\n    <div class=\"description\">\n        <p>\n        "
    i=i+1 out[i] = Filter.html(get(get(stash, 'pkg_info'), 'abstract'))
    i=i+1 out[i] = "\n        </p>\n    </div>\n</div>\n\n<div class=\"metadata_columns\">\n    <div class=\"metadata_columns_inner\">\n        <div class=\"column\">\n            <h3>Account</h3>"
    i=i+1 out[i] = get(stash, 'account')
    i=i+1 out[i] = "\n        </div>\n        <div class=\"column\">\n            <h3>Repo</h3><a href=\""
    i=i+1 out[i] = get(get(stash, 'pkg_info'), 'repo_link')
    i=i+1 out[i] = "\" target=\"_blank\">"
    i=i+1 out[i] = get(get(stash, 'pkg_info'), 'repo_link')
    i=i+1 out[i] = "</a>\n        </div>\n    </div>\n</div>\n\n<div class=\"installer\">\n    <pre class=\"highlight lang_bash term_snippet\"><code><span class=\"nv\">$ </span>opm get "
    i=i+1 out[i] = get(stash, 'account')
    i=i+1 out[i] = "/"
    i=i+1 out[i] = Filter.html(get(stash, 'pkg_name'))
    i=i+1 out[i] = "</code></pre>\n</div>\n\n<div>\n"
    i=i+1 out[i] = get(stash, 'pkg_doc')
    i=i+1 out[i] = "\n</div>\n\n<h3>Authors</h3>\n<div class=\"description\">\n    <p>\n    "
    i=i+1 out[i] = Filter.html(get(get(stash, 'pkg_info'), 'authors'))
    i=i+1 out[i] = "\n    </p>\n<div>\n\n<h3>License</h3>\n<div class=\"description\">\n    <p>\n    "
    i=i+1 out[i] = Filter.html(get(get(stash, 'pkg_info'), 'licenses'))
    i=i+1 out[i] = "\n    </p>\n<div>\n"

    if tru(get(get(stash, 'pkg_info'), 'dep_info')) then
        i=i+1 out[i] = "\n<h3>Dependencies</h3>\n<div class=\"description\">\n    <p>\n    "
        i=i+1 out[i] = get(get(stash, 'pkg_info'), 'dep_info')
        i=i+1 out[i] = "\n    </p>\n</div>"
    end

    i=i+1 out[i] = "\n\n<h3>Versions</h3>\n\n<section>\n"
    i=i+1 out[i] = process(stash, "package_list.tt2")
    i=i+1 out[i] = "\n</section>\n</div>\n"

    return out
end

MD5['package_info.tt2'] = "cdeaa38b342208b9feeb6128af27a228"

Template['package_list.tt2'] = function (stash)
    local out = {}
    local i = 0
    i=i+1 out[i] = "\n<ul class=\"package_list\">\n"

    for item in each(get(stash, 'packages')) do
        set(stash, 'row', item)
        i=i+1 out[i] = "\n<li class=\"package_row\">\n\n    "
        set(stash, 'pkg_uploader_name', get(get(stash, 'row'), 'uploader_name'))
        set(stash, 'org', get(get(stash, 'row'), 'org_name'))
        set(stash, 'account', get(stash, 'pkg_uploader_name'))

        if tru(get(stash, 'org')) then
            set(stash, 'account', get(stash, 'org'))
        end

        i=i+1 out[i] = "\n\n    <div class=\"main\">"

        if tru(get(get(stash, 'row'), 'raw_package_name')) then
            i=i+1 out[i] = "\n        <a href=\"/package/"
            i=i+1 out[i] = ((get(stash, 'account') .. "/") .. get(get(stash, 'row'), 'raw_package_name'))
            i=i+1 out[i] = "/\" class=\"title\">"

        else
            i=i+1 out[i] = "\n        <a href=\"/package/"
            i=i+1 out[i] = ((get(stash, 'account') .. "/") .. get(get(stash, 'row'), 'package_name'))
            i=i+1 out[i] = "/\" class=\"title\">"
        end

        i=i+1 out[i] = "\n\n            "
        i=i+1 out[i] = ((get(stash, 'account') .. "/") .. get(get(stash, 'row'), 'package_name'))
        i=i+1 out[i] = "\n        </a>\n        <span class=\"version_name\">\n            "
        i=i+1 out[i] = Filter.html(get(get(stash, 'row'), 'version_s'))
        i=i+1 out[i] = "\n        </span>"

        if tru((((tru(get(stash, 'uploader_page')) and tru(get(stash, 'curr_user'))) and tru(get(stash, 'uploader_name'))) and (get(stash, 'uploader_name') == get(get(stash, 'curr_user'), 'login')))) then
            i=i+1 out[i] = "\n"

            if tru(not tru(get(get(stash, 'row'), 'is_deleted'))) then
                i=i+1 out[i] = "\n        <span class=\"delete-pkg\" item-pkg-name=\""
                i=i+1 out[i] = get(get(stash, 'row'), 'package_name')
                i=i+1 out[i] = "\" item-pkg-account=\""
                i=i+1 out[i] = get(stash, 'account')
                i=i+1 out[i] = "\" title=\"delete this pkg\"><img src=\"/images/delete.png\" class=\"delete-btn\"></span>"
            end

            if tru(get(get(stash, 'row'), 'is_deleted')) then
                i=i+1 out[i] = "\n            <span class=\"failed\">pending deleting</span>\n            <span class=\"cancel-deleting-pkg\" item-pkg-name=\""
                i=i+1 out[i] = get(get(stash, 'row'), 'package_name')
                i=i+1 out[i] = "\" item-pkg-account=\""
                i=i+1 out[i] = get(stash, 'account')
                i=i+1 out[i] = "\" title=\"cancel deleting this pkg\"><img src=\"/images/cancel.png\" class=\"cancel-deleting-btn\"></span>"
            end

            i=i+1 out[i] = "\n"
        end

        i=i+1 out[i] = "\n"

        if tru(get(get(stash, 'row'), 'indexed')) then
            i=i+1 out[i] = "\n"

        elseif tru(get(get(stash, 'row'), 'failed')) then
            i=i+1 out[i] = "\n        <span class=\"failed\">Failed</span>"

        else
            i=i+1 out[i] = "\n        <span class=\"pending\">Pending</span>"
        end

        i=i+1 out[i] = "\n        <span class=\"author\">\n            by \n            <a href=\"/uploader/"
        i=i+1 out[i] = get(stash, 'pkg_uploader_name')
        i=i+1 out[i] = "/\">\n                "
        i=i+1 out[i] = get(stash, 'pkg_uploader_name')
        i=i+1 out[i] = "\n            </a>\n        </span>\n    </div>\n    <div class=\"summary\">\n        "
        i=i+1 out[i] = get(get(stash, 'row'), 'abstract')
        i=i+1 out[i] = "\n        <span class=\"updated_at\">\n            "
        i=i+1 out[i] = Filter.html(get(get(stash, 'row'), 'upload_updated_at'))
        i=i+1 out[i] = "\n        </span>\n    </div>\n</li>"
    end

    i=i+1 out[i] = "\n</ul>\n\n"
    i=i+1 out[i] = get(stash, 'page_info')
    i=i+1 out[i] = "\n"

    return out
end

MD5['package_list.tt2'] = "ffe7761ab9e4400c3c037ce33478fc30"

Template['packages.tt2'] = function (stash)
    local out = {}
    local i = 0
    i=i+1 out[i] = "\n<div class=\"main_col\">\n<div class=\"split_header\">\n    <h2>Recent packages\n    <span class=\"right\">\n      <a href=\"/uploads\">Recent uploads</a>\n    </span>\n    </h2>\n</div>\n\n"
    i=i+1 out[i] = process(stash, "package_list.tt2")
    i=i+1 out[i] = "\n</div>\n"

    return out
end

MD5['packages.tt2'] = "5025e994ada6508f133c9d49f5ac6000"

Template['search.tt2'] = function (stash)
    local out = {}
    local i = 0
    i=i+1 out[i] = "\n<div class=\"main_col\">\n<div class=\"split_header\">\n    <h2>Search results</h2>\n</div>\n\n"
    i=i+1 out[i] = process(stash, "package_list.tt2")
    i=i+1 out[i] = "\n</div>\n"

    return out
end

MD5['search.tt2'] = "3dab5a9a73c855203aec6711012bc365"

Template['success.tt2'] = function (stash)
    local out = {}
    local i = 0
    i=i+1 out[i] = "\n<div class=\"main_col\">\n<div class=\"split_header\">\n    <h2>Success</h2>\n</div>\n\n<div class=\"success_info\">\n    "
    i=i+1 out[i] = Filter.html(get(stash, 'success_info'))
    i=i+1 out[i] = "\n</div>\n\n</div>\n"

    return out
end

MD5['success.tt2'] = "7a03714f806ba10eb2a7b9839dc94695"

Template['uploader.tt2'] = function (stash)
    local out = {}
    local i = 0
    i=i+1 out[i] = "\n<div class=\"main_col\">\n<div class=\"split_header\">\n    <h2>"
    i=i+1 out[i] = Filter.html(get(stash, 'uploader_name'))
    i=i+1 out[i] = "\n    </h2>\n    <span class=\"user_github\">\n      <a href=\"https://github.com/"
    i=i+1 out[i] = Filter.html(get(stash, 'uploader_name'))
    i=i+1 out[i] = "/\" target=\"_blank\"><img src=\"/images/github.png\" width=\"30\" height=\"30\" alt=\"GitHub\"></a>\n    </span>\n</div>\n\n<div class=\"metadata_columns\">\n    <div class=\"metadata_columns_inner\">\n        <div class=\"column\">\n            <h3>Packages</h3>"
    i=i+1 out[i] = get(stash, 'packages_count')
    i=i+1 out[i] = "\n        </div>"

    if tru(get(get(stash, 'uploader'), 'public_email')) then
        i=i+1 out[i] = "\n        <div class=\"column\">\n            <h3>Email</h3>"
        i=i+1 out[i] = get(get(stash, 'uploader'), 'public_email')
        i=i+1 out[i] = "\n        </div>"
    end

    if tru(get(get(stash, 'uploader'), 'blog')) then
        i=i+1 out[i] = "\n        <div class=\"column\">\n            <h3>Blog</h3><a href=\""
        i=i+1 out[i] = get(get(stash, 'uploader'), 'blog')
        i=i+1 out[i] = "\" target=\"_blank\">"
        i=i+1 out[i] = get(get(stash, 'uploader'), 'blog')
        i=i+1 out[i] = "</a>\n        </div>"
    end

    i=i+1 out[i] = "\n    </div>\n</div>\n\n<h3>Packages</h3>\n\n<section>\n"
    i=i+1 out[i] = process(stash, "package_list.tt2")
    i=i+1 out[i] = "\n</section>\n\n<script>\n$(document).ready(function(){\n    $('.package_row .delete-pkg').click(function(){\n        var pkg_name=$(this).attr('item-pkg-name');\n        var pkg_account=$(this).attr('item-pkg-account');\n        if(confirm('delete package ' + pkg_name + '?')) {\n            var params = {\n                pkg_name: pkg_name,\n                pkg_account: pkg_account,\n            };\n            $.ajax({\n                type: \"POST\",\n                url: '/api_delete_pkg/',\n                dataType: \"json\",\n                data: JSON.stringify(params),\n                success:function(resp){\n                    var status = resp.status;\n                    if (status == 0) {\n                        alert(resp.data);\n                    }\n                    else {\n                        alert(resp.msg);\n                    }\n                    window.location.reload();\n                }\n            });\n        }\n    });\n\n    $('.package_row .cancel-deleting-pkg').click(function(){\n        var pkg_name=$(this).attr('item-pkg-name');\n        var pkg_account=$(this).attr('item-pkg-account');\n        if(confirm('cancel deleting package ' + pkg_name + '?')) {\n            var params = {\n                pkg_name: pkg_name,\n                pkg_account: pkg_account,\n            };\n            $.ajax({\n                type: \"POST\",\n                url: '/api_cancel_deleting_pkg/',\n                dataType: \"json\",\n                data: JSON.stringify(params),\n                success:function(resp){\n                    var status = resp.status;\n                    if (status == 0) {\n                        alert(resp.data);\n                    }\n                    else {\n                        alert(resp.msg);\n                    }\n                    window.location.reload();\n                }\n            });\n        }\n    });\n});\n</script>\n\n</div>\n"

    return out
end

MD5['uploader.tt2'] = "203c07c8ce1e32ca73f36d10ec6f6d9b"

Template['uploads.tt2'] = function (stash)
    local out = {}
    local i = 0
    i=i+1 out[i] = "\n<div class=\"main_col\">\n<div class=\"split_header\">\n    <h2>Recent uploads</h2>\n    <span class=\"right\">\n      <a href=\"/packages\">Recent packages</a>\n    </span>\n</div>\n\n"
    i=i+1 out[i] = process(stash, "package_list.tt2")
    i=i+1 out[i] = "\n</div>\n"

    return out
end

MD5['uploads.tt2'] = "2b4863d172247c6fece2db01043a2e2d"


-- Return the Lemplate module exports table:
return Lemplate
